version: '3.8'

services:
  deepwiki:
    build: .
    ports:
      - "${PORT:-8001}:8001"  # API port (backend)
      - "3000:3000"           # Next.js port (frontend)
    env_file:
      - .env
    environment:
      - PORT=${PORT:-8001}
      - NODE_ENV=production
      - NEXT_PUBLIC_SERVER_BASE_URL=http://localhost:${PORT:-8001}
    volumes:
      - wiki-data:/app/wiki-data  # Persist all embeddings, repos, and wikis
      - chromadb-data:/app/wiki-data/chromadb  # Persist ChromaDB vector database

volumes:
  wiki-data:
    driver: local
  chromadb-data:
    driver: local
